apiVersion: apps/v1
kind: Deployment
metadata:
  name: change-data-capture
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "change-data-capture.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "change-data-capture.selectorLabels" . | nindent 6 }}  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{.Values.maxSurge}}
      maxUnavailable: {{.Values.maxUnavailable}}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "change-data-capture.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "change-data-capture.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 30
      initContainers:
      - name: wait
        image: busybox:1.35.0
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', "sleep 420"]
      containers:
        - name: change-data-capture
          image: {{ include "harnesscommon.names.imagename" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
              {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: harness-secrets
                  key: mongodbUsername
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: harness-secrets
                  key: mongodbPassword
            - name : TIMESCALEDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: harness-secrets
                  key: timescaledbPostgresPassword
            - name: TIMESCALEDB_USERNAME
              value: postgres                           
            - name: MONGO_URI
              value: {{ include "harnesscommon.database.mongo" (dict "database" "harness" "context" $) }}
            - name: EVENTS_MONGO_URI
              value: {{ include "harnesscommon.database.mongo" (dict "database" "events" "context" $) }}
            - name: PMS_MONGO_URI
              value: {{ include "harnesscommon.database.mongo" (dict "database" "pms-harness" "context" $) }}
            - name: CDC_MONGO_URI
              value: {{ include "harnesscommon.database.mongo" (dict "database" "change-data-capture" "context" $) }}
            - name: NG_HARNESS_MONGO_URI
              value: {{ include "harnesscommon.database.mongo" (dict "database" "ng-harness" "context" $) }}
            - name: TIMESCALEDB_URI
              value: 'jdbc:postgresql://timescaledb-single-chart.{{ .Release.Namespace }}:5432/harness'
          envFrom:
          - configMapRef:
              name: change-data-capture
          resources:
              {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{.Values.service.port}}
            initialDelaySeconds: 300
            timeoutSeconds: 10
            periodSeconds: 10
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: /health
              port: {{.Values.service.port}}
            initialDelaySeconds: 400
            timeoutSeconds: 10
            periodSeconds: 10
            failureThreshold: 10
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - change-data-capture
            topologyKey: "kubernetes.io/hostname"
      {{- with .Values.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}